### PR TITLE
Dthakkar/tri 80 modify lettergrade background colour based on score

### PR DESCRIPTION
**Pull request by dhairya-t**
allow the background of the fariness score card comp to change colors based on the actual percentage. Had to modify some code to ensure we were returning and using percentage

### CODE REVIEW

**Comment by dhairya-t** [comment]
Screenshot 2024-11-18 at 7 21 31 PM

**Comment by aakshataa** [comment]
Are the only letter grade colours red, green and blue?

**Comment by aakshataa** [comment]
> Are the only letter grade colours red, green and blue?

Okay I think I see what's going on, right now the colours will range between red and green rather than red orange, yellow, green (and every shade in between). I think to fix this (since scores of B or C will just have a brown background), there can be 3-4 'ranges' of colour, and depending on the percentage the colour will be in a certain range.

**Review by 1zhaohel — COMMENTED** [review]
haha 🤣 (the colour does not show)
Screenshot 2024-11-21 at 10 36 24 AM

**Comment by dhairya-t** [comment]
> https://deploy-preview-45--byebyebias.netlify.app



> > Are the only letter grade colours red, green and blue?
> 
> Okay I think I see what's going on, right now the colours will range between red and green rather than red orange, yellow, green (and every shade in between). I think to fix this (since scores of B or C will just have a brown background), there can be 3-4 'ranges' of colour, and depending on the percentage the colour will be in a certain range.
> 
> Then using the same code as in the BiasScore function you can get the specific hex code

that makes sense! i fixed it now and it ranges properly, thanks :)

**Comment by dhairya-t** [comment]
> haha 🤣 Screenshot 2024-11-21 at 10 36 24 AM
C1BbXotRGF0ZT0yMDI0MTEyM1QwMTA5MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMjU0NGQ3NDZkNjE3N2NlYjdkNGM5MGViOGUwODVjOWFhNTdiNTRmNDIxZDE0NDQ0MTQ4MmZhZjFhZGQzMzNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.g1Y8BuxYcZHFdEFt-nga2infmQ7y9XjxWZFORvvsTUw">

**Review by aakshataa — APPROVED** [review]
looks good!

**Review by chloehylee — CHANGES_REQUESTED** [review]
looks good!

**Review by aerymist — APPROVED** [review]

**Pull request merged**
